version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:90
    environment:
      - PMA_ARBITRARY=1

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  wordpress:
  phpmyadmin:
  db:

networks:
  default:
    name: my-main-net
    external: true
